[project]
name = "etl-wikipedia-updates"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "pyyaml>=6.0.3",
    "sseclient>=0.0.27",
    "streamlit>=1.52.2",
]
